# Generated by Django 4.2.5 on 2024-07-16 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tethys_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActionType',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='channelType',
        ),
        migrations.DeleteModel(
            name='ScheduleType',
        ),
        migrations.DeleteModel(
            name='TransmissionPowerLevel',
        ),
        migrations.DeleteModel(
            name='Channel',
        ),
        migrations.DeleteModel(
            name='ChannelType',
        ),
    ]
