# Generated by Django 4.2.5 on 2024-07-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tethys_api', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actiontype',
            name='id',
        ),
        migrations.RemoveField(
            model_name='channeltype',
            name='id',
        ),
        migrations.RemoveField(
            model_name='scheduletype',
            name='id',
        ),
        migrations.RemoveField(
            model_name='transmissionpowerlevel',
            name='id',
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='startTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='actiontype',
            name='name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='channeltype',
            name='name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='scheduletype',
            name='name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transmissionpowerlevel',
            name='name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
