# Generated by Django 5.0.7 on 2024-08-03 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionType',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('enabled', models.BooleanField(default=False)),
                ('nickName', models.CharField(blank=True, default='New Channel', max_length=100)),
                ('actionTriggerPercent', models.IntegerField()),
                ('pumpDurationSeconds', models.IntegerField()),
                ('sensorMeasureFrequencyMinutes', models.IntegerField()),
                ('sensorTriggerCalibration', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ChannelType',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleType',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransmissionPowerLevel',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('value', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField(null=True)),
                ('endTime', models.DateTimeField(null=True)),
                ('actionType', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tethys_api.actiontype')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tethys_api.channel')),
            ],
        ),
        migrations.AddField(
            model_name='channel',
            name='channelType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tethys_api.channeltype'),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('weekday', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=20)),
                ('startTime', models.DateTimeField()),
                ('durationMinutes', models.SmallIntegerField()),
                ('scheduleType', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tethys_api.scheduletype')),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batteryVoltage', models.FloatField()),
                ('moisturePercent', models.SmallIntegerField()),
                ('timestamp', models.DateTimeField(null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tethys_api.channel')),
            ],
        ),
        migrations.AddField(
            model_name='channel',
            name='sensorTransmissionPowerLevel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tethys_api.transmissionpowerlevel'),
        ),
    ]
