"""
Django settings for tethys_api project.

Generated by 'django-admin startproject' using Django 4.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Make the shared `globals` package (code/master/globals) importable here.
# BASE_DIR is the `api/` directory, so its parent is `code/master`. The core
# process already adds the same dir to sys.path; this lets settings (which runs
# before views.py) read the single git-ignored secrets file.
MASTER_DIR = BASE_DIR.parent
if str(MASTER_DIR) not in sys.path:
    sys.path.insert(0, str(MASTER_DIR))

try:
    from globals.secrets import TETHYS_API_KEY
except ImportError as exc:  # pragma: no cover - configuration error path
    raise ImportError(
        "Missing globals/secrets.py. Copy code/master/globals/secrets.example.py "
        "to code/master/globals/secrets.py and set TETHYS_API_KEY (or run "
        "install/install.sh, which generates it)."
    ) from exc


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-hx!=+4j#v*^*^3ls=-b5f_91c$)k%spgqodtk)f!t)@$4t%=)@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
    "tethys.local",
]


# Application definition

INSTALLED_APPS = [
    'tethys_api',
    'rest_framework',
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = True

# The web UI (different origin/port) sends the key as a custom request header,
# which must be explicitly allow-listed for CORS even with all origins allowed.
from corsheaders.defaults import default_headers
CORS_ALLOW_HEADERS = list(default_headers) + ["x-api-key"]

# Require the shared API key (X-API-Key header) on all mutating requests; reads
# stay open. No session/BasicAuth so DRF's SessionAuthentication CSRF check never
# engages for these header-authenticated, cookie-less calls.
REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": ["tethys_api.permissions.ApiKeyForWrite"],
    "DEFAULT_AUTHENTICATION_CLASSES": [],
}

ROOT_URLCONF = 'tethys_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tethys_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Sourced from the single canonical definition (globals/config.py) so the API
# stores/interprets schedule times in the same zone the core localizes the
# silent-phase window against. The `globals` package is already on sys.path
# (set up above for globals.secrets). Was a hardcoded 'UTC' that diverged from
# the core/web 'Europe/Stockholm' and broke the silent-phase window.
from globals.config import TIME_ZONE

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
